# This sends the players with the perm 'hungergames.respawn' back to spawn
# Set it less then 0 to disable
RespawnDuration: -1
# Does his items regenerate as well
RespawnItems: true

CactusJuice: false
CactusJuiceName: '&fCactus Juice'
CactusJuiceRestores: 6

ChocolateMilk: false
ChocolateMilkName: '&fChocolate Milk'
ChocolateMilkRestores: 6

# Shall the winner appear on a platform full of delicious tasty cake?
CakeForWinners: false

# Shall the feast chests be generated just like MCPVP
# You can already change the type of material the feast looks like.
McpvpFeast: false